version: 0.2

phases:
    pre_build:
        conmmands:
            - echo Logging into ECR
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 008887957957.dkr.ecr.us-east-1.amazonaws.com
    build:
        commands:
            - echo Starting build at `date`
            - echo Building the Docker image...
            - docker build -t project3
            - docker tag project3:latest 008887957957.dkr.ecr.us-east-1.amazonaws.com/analytics:latest
    post_build:
        commands:
            - echo Completed build at `date`
            - echo Pusing the Docker image...
            - docker push 008887957957.dkr.ecr.us-east-1.amazonaws.com/analytics:latest
